<?xml version="1.0" encoding="utf-8"?><Database Name="LTUDQL" Class="QLTNDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.CapHoc" Member="CapHocs">
    <Type Name="CapHoc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tencap" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="CapHoc_CapHoc_MonHoc" Member="CapHoc_MonHocs" ThisKey="id" OtherKey="caphocid" Type="CapHoc_MonHoc" />
      <Association Name="CapHoc_LopHoc" Member="LopHocs" ThisKey="id" OtherKey="caphocid" Type="LopHoc" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tentaikhoan" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="permission" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lophocid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TaiKhoan_CauHoi" Member="CauHois" ThisKey="id" OtherKey="donggop" Type="CauHoi" />
      <Association Name="TaiKhoan_HocSinhLamBai" Member="HocSinhLamBais" ThisKey="id" OtherKey="hocsinhid" Type="HocSinhLamBai" />
      <Association Name="TaiKhoan_HocSinhThamGia" Member="HocSinhThamGias" ThisKey="id" OtherKey="hocsinhid" Type="HocSinhThamGia" />
      <Association Name="LopHoc_TaiKhoan" Member="LopHoc" ThisKey="lophocid" OtherKey="id" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CapHoc_MonHoc" Member="CapHoc_MonHocs">
    <Type Name="CapHoc_MonHoc">
      <Column Name="caphocid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="monhocid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CapHoc_MonHoc_CauHoi" Member="CauHois" ThisKey="caphocid,monhocid" OtherKey="caphocid,monhocid" Type="CauHoi" />
      <Association Name="CapHoc_MonHoc_DeThi" Member="DeThis" ThisKey="caphocid,monhocid" OtherKey="caphocid,monhocid" Type="DeThi" />
      <Association Name="CapHoc_CapHoc_MonHoc" Member="CapHoc" ThisKey="caphocid" OtherKey="id" Type="CapHoc" IsForeignKey="true" />
      <Association Name="MonHoc_CapHoc_MonHoc" Member="MonHoc" ThisKey="monhocid" OtherKey="id" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="goiy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dokho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="caphocid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="monhocid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donggop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CauHoi_DapAn" Member="DapAns" ThisKey="id" OtherKey="cauhoiid" Type="DapAn" />
      <Association Name="CauHoi_DeThi_CauHoi" Member="DeThi_CauHois" ThisKey="id" OtherKey="cauhoiid" Type="DeThi_CauHoi" />
      <Association Name="CapHoc_MonHoc_CauHoi" Member="CapHoc_MonHoc" ThisKey="caphocid,monhocid" OtherKey="caphocid,monhocid" Type="CapHoc_MonHoc" IsForeignKey="true" />
      <Association Name="TaiKhoan_CauHoi" Member="TaiKhoan" ThisKey="donggop" OtherKey="id" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DapAn" Member="DapAns">
    <Type Name="DapAn">
      <Column Name="cauhoiid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stt" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dungsai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CauHoi_DapAn" Member="CauHoi" ThisKey="cauhoiid" OtherKey="id" Type="CauHoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi" Member="DeThis">
    <Type Name="DeThi">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="loaidethi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoigiantoida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="caphocid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="monhocid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kythiid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DeThi_DeThi_CauHoi" Member="DeThi_CauHois" ThisKey="id" OtherKey="dethiid" Type="DeThi_CauHoi" />
      <Association Name="DeThi_HocSinhThamGia" Member="HocSinhThamGias" ThisKey="id" OtherKey="dethiid" Type="HocSinhThamGia" />
      <Association Name="CapHoc_MonHoc_DeThi" Member="CapHoc_MonHoc" ThisKey="caphocid,monhocid" OtherKey="caphocid,monhocid" Type="CapHoc_MonHoc" IsForeignKey="true" />
      <Association Name="KyThi_DeThi" Member="KyThi" ThisKey="kythiid" OtherKey="id" Type="KyThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi_CauHoi" Member="DeThi_CauHois">
    <Type Name="DeThi_CauHoi">
      <Column Name="dethiid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cauhoiid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DeThi_CauHoi_HocSinhLamBai" Member="HocSinhLamBais" ThisKey="dethiid,cauhoiid" OtherKey="dethiid,cauhoiid" Type="HocSinhLamBai" />
      <Association Name="CauHoi_DeThi_CauHoi" Member="CauHoi" ThisKey="cauhoiid" OtherKey="id" Type="CauHoi" IsForeignKey="true" />
      <Association Name="DeThi_DeThi_CauHoi" Member="DeThi" ThisKey="dethiid" OtherKey="id" Type="DeThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocSinhLamBai" Member="HocSinhLamBais">
    <Type Name="HocSinhLamBai">
      <Column Name="hocsinhid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dethiid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cauhoiid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dungsai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DeThi_CauHoi_HocSinhLamBai" Member="DeThi_CauHoi" ThisKey="dethiid,cauhoiid" OtherKey="dethiid,cauhoiid" Type="DeThi_CauHoi" IsForeignKey="true" />
      <Association Name="TaiKhoan_HocSinhLamBai" Member="TaiKhoan" ThisKey="hocsinhid" OtherKey="id" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocSinhThamGia" Member="HocSinhThamGias">
    <Type Name="HocSinhThamGia">
      <Column Name="hocsinhid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dethiid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="socaudung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoigianlambai" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DeThi_HocSinhThamGia" Member="DeThi" ThisKey="dethiid" OtherKey="id" Type="DeThi" IsForeignKey="true" />
      <Association Name="TaiKhoan_HocSinhThamGia" Member="TaiKhoan" ThisKey="hocsinhid" OtherKey="id" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KyThi" Member="KyThis">
    <Type Name="KyThi">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenkythi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="KyThi_DeThi" Member="DeThis" ThisKey="id" OtherKey="kythiid" Type="DeThi" />
    </Type>
  </Table>
  <Table Name="dbo.LopHoc" Member="LopHocs">
    <Type Name="LopHoc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="caphocid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LopHoc_TaiKhoan" Member="TaiKhoans" ThisKey="id" OtherKey="lophocid" Type="TaiKhoan" />
      <Association Name="CapHoc_LopHoc" Member="CapHoc" ThisKey="caphocid" OtherKey="id" Type="CapHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenmonhoc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="MonHoc_CapHoc_MonHoc" Member="CapHoc_MonHocs" ThisKey="id" OtherKey="monhocid" Type="CapHoc_MonHoc" />
    </Type>
  </Table>
</Database>